use_frameworks!

platform :ios, '10.0'

target 'CoinliveChatUIKit_Example' do
  pod 'CoinliveChatUIKit', :path => '../'

  target 'CoinliveChatUIKit_Tests' do
    inherit! :search_paths

    
  end
end
